pub fn error_from_code_win32(code: u32) -> String {
    match code {
        0 => "SUCCESS".to_string(),
        2 => "FILE_NOT_FOUND".to_string(),
        5 => "ACCESS_DENIED".to_string(),
        6 => "INVALID_HANDLE".to_string(),
        8 => "NOT_ENOUGH_MEMORY".to_string(),
        31 => "ERROR_GEN_FAILURE".to_string(),
        87 => "INVALID_PARAMETER".to_string(),
        122 => "INSUFFICIENT_BUFFER".to_string(),
        126 => "MOD_NOT_FOUND".to_string(),
        127 => "PROC_NOT_FOUND".to_string(),
        193 => "BAD_EXE_FORMAT".to_string(),
        565 => "TOO_MANY_THREADS".to_string(),
        566 => "THREAD_NOT_IN_PROCESS".to_string(),
        567 => "PAGEFILE_QUOTA_EXCEEDED".to_string(),
        571 => "IO_PRIVILEGE_FAILED".to_string(),
        577 => "INVALID_IMAGE_HASH".to_string(),
        633 => "DRIVER_FAILED_SLEEP".to_string(),
        998 => "NOACCESS".to_string(),
        1003 => "CALLER_CANNOT_MAP_VIEW".to_string(),
        1006 => "VOLUME_CHANGED".to_string(),
        1007 => "FULLSCREEN_MODE".to_string(),
        1008 => "INVALID_HANDLE_STATE".to_string(),
        1058 => "SERVICE_DISABLED".to_string(),
        1060 => "SERVICE_DOES_NOT_EXIST".to_string(),
        1062 => "SERVICE_NOT_STARTED".to_string(),
        1073 => "ALREADY_RUNNING".to_string(),
        1314 => "PRIVILEGE_NOT_HELD".to_string(),
        1330 => "INVALID_ACCOUNT_NAME".to_string(),
        1331 => "LOGON_FAILURE".to_string(),
        1332 => "ACCOUNT_RESTRICTION".to_string(),
        1344 => "NO_LOGON_SERVERS".to_string(),
        1346 => "RPC_AUTH_LEVEL_MISMATCH".to_string(),
        1444 => "INVALID_THREAD_ID".to_string(),
        1445 => "NON_MDICHILD_WINDOW".to_string(),
        1450 => "NO_SYSTEM_RESOURCES".to_string(),
        1460 => "TIMEOUT".to_string(),
        1453 => "QUOTA_EXCEEDED".to_string(),
        1455 => "PAGEFILE_TOO_SMALL".to_string(),
        1500 => "EVT_INVALID_CHANNEL".to_string(),
        1503 => "EVT_CHANNEL_ALREADY_EXISTS".to_string(),

        _ => format!("WIN32_ERROR_CODE_0x{:08X}", code),
    }
}
pub fn error_from_ntstatus(status: i32) -> String {
    match i32::cast_unsigned(status) {
        0 => "STATUS_SUCCESS".to_string(),
        1 => "STATUS_WAIT_1".to_string(),

        0xC0000001 => "STATUS_UNSUCCESSFUL".to_string(),
        0xC0000002 => "STATUS_NOT_IMPLEMENTED".to_string(),
        0xC0000003 => "STATUS_INVALID_INFO_CLASS".to_string(),
        0xC0000004 => "STATUS_INFO_LENGTH_MISMATCH".to_string(),
        0xC0000008 => "STATUS_INVALID_HANDLE".to_string(),
        0xC000000D => "STATUS_INVALID_PARAMETER".to_string(),
        0xC0000017 => "STATUS_NO_MEMORY".to_string(),
        0xC0000018 => "STATUS_CONFLICTING_ADDRESSES".to_string(),
        0xC0000022 => "STATUS_ACCESS_DENIED".to_string(),
        0xC0000023 => "STATUS_BUFFER_TOO_SMALL".to_string(),
        0xC0000034 => "STATUS_OBJECT_NAME_NOT_FOUND".to_string(),
        0xC000004B => "STATUS_THREAD_IS_TERMINATING".to_string(),
        0xC0000061 => "STATUS_PRIVILEGE_NOT_HELD".to_string(),
        0xC00000BB => "STATUS_NOT_SUPPORTED".to_string(),
        0xC000010A => "STATUS_PROCESS_IS_TERMINATING".to_string(),

        _ => format!("NTSTATUS_0x{:08X}", status as u32),
    }
}
