mod apply;
mod cli;
mod config;
mod logging;
mod priority;
mod process;
mod scheduler;
mod winapi;

use apply::{
    ApplyConfigResult, apply_affinity, apply_ideal_processors, apply_io_priority, apply_memory_priority, apply_prime_threads, apply_priority,
    apply_process_default_cpuset,
};
use chrono::Local;
use cli::{CliArgs, parse_args, print_help, print_help_all};
use config::{ProcessConfig, convert, read_config, read_list};
use encoding_rs::Encoding;
use logging::{
    DUST_BIN_MODE, FAIL_SET, LOCALTIME_BUFFER, error_from_code, find_logger, log_message, log_process_find, log_pure_message, log_to_find, logger, use_console,
};
use process::ProcessSnapshot;
use scheduler::PrimeThreadScheduler;
use std::{
    collections::{HashMap, HashSet},
    env,
    io::Write,
    mem::size_of,
    process::Command,
    thread,
    time::Duration,
};
use winapi::{NtSetTimerResolution, enable_debug_privilege, enable_inc_base_priority_privilege, is_affinity_unset, is_running_as_admin, request_uac_elevation};
use windows::Win32::{
    Foundation::{CloseHandle, GetLastError},
    System::{
        Console::GetConsoleOutputCP,
        Diagnostics::ToolHelp::{CreateToolhelp32Snapshot, PROCESSENTRY32W, Process32FirstW, Process32NextW, TH32CS_SNAPPROCESS},
        Threading::{OpenProcess, PROCESS_QUERY_INFORMATION, PROCESS_SET_INFORMATION},
    },
};

fn apply_config(
    pid: u32,
    config: &ProcessConfig,
    prime_core_scheduler: &mut PrimeThreadScheduler,
    mut processes: Option<&mut ProcessSnapshot>,
    dry_run: bool,
) -> ApplyConfigResult {
    let mut apply_config_result = ApplyConfigResult::new();
    let access_flags = if dry_run {
        PROCESS_QUERY_INFORMATION
    } else {
        PROCESS_SET_INFORMATION | PROCESS_QUERY_INFORMATION
    };
    let open_result = unsafe { OpenProcess(access_flags, false, pid) };
    let h_prc = match open_result {
        Err(_) => {
            let error_code = unsafe { GetLastError().0 };
            if dry_run {
                apply_config_result.add_change("[SKIP] OpenProcess failed".to_owned());
            } else {
                apply_config_result.add_error(format!("apply_config: [OPEN][{}] {:>5}-{}", error_from_code(error_code), pid, config.name));
            }
            return apply_config_result;
        }
        Ok(h_prc) => h_prc,
    };
    if h_prc.is_invalid() {
        if dry_run {
            apply_config_result.add_change("[SKIP] Invalid handle".to_owned());
            return apply_config_result;
        }
        apply_config_result.add_error(format!("apply_config: [INVALID_HANDLE] {:>5}-{}", pid, config.name));
        return apply_config_result;
    }
    let mut current_mask: usize = 0;
    apply_priority(pid, config, dry_run, h_prc, &mut apply_config_result);
    apply_affinity(pid, config, dry_run, h_prc, &mut current_mask, &mut apply_config_result, &mut processes);
    apply_process_default_cpuset(pid, config, dry_run, h_prc, &mut apply_config_result);
    apply_prime_threads(
        pid,
        config,
        prime_core_scheduler,
        &mut processes,
        dry_run,
        &mut current_mask,
        &mut apply_config_result,
    );
    apply_io_priority(pid, config, dry_run, h_prc, &mut apply_config_result);
    apply_memory_priority(pid, config, dry_run, h_prc, &mut apply_config_result);
    apply_ideal_processors(pid, config, &mut processes, prime_core_scheduler, dry_run, &mut apply_config_result);
    let _ = unsafe { CloseHandle(h_prc) };
    apply_config_result
}

fn process_logs(configs: &HashMap<u32, HashMap<String, ProcessConfig>>, blacklist: &[String], logs_path: Option<&str>, output_file: Option<&str>) {
    // Processes logs to discover new processes not yet in config or blacklist, and searches for their file paths.
    //
    // # Requirements
    // - Everything search tool installed with `es.exe` in PATH
    // - Log files in the logs directory (generated by `-find` mode)
    *use_console().lock().unwrap() = true;
    let logs_path = logs_path.unwrap_or("logs");
    let output_file = output_file.unwrap_or("new_processes_results.txt");

    // Get all unique processes from logs
    let mut all_processes = HashSet::new();
    if let Ok(entries) = std::fs::read_dir(logs_path) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.file_name().and_then(|n| n.to_str()).is_some_and(|n| n.ends_with(".find.log"))
                && let Ok(content) = std::fs::read_to_string(&path)
            {
                for line in content.lines() {
                    if let Some(idx) = line.find("find ") {
                        let rest = &line[idx + 5..];
                        let proc = if let Some(space_idx) = rest.find(' ') { &rest[..space_idx] } else { rest.trim() };
                        if proc.ends_with(".exe") {
                            all_processes.insert(proc.to_lowercase());
                        }
                    }
                }
            }
        }
    }
    // Check if process exists in any grade bucket
    let in_any_grade = |p: &String| configs.values().any(|grade_configs| grade_configs.contains_key(p));
    let new_processes: Vec<String> = all_processes.into_iter().filter(|p| !in_any_grade(p) && !blacklist.contains(p)).collect();

    // Search with es
    let mut output = String::new();
    let acp = unsafe { GetConsoleOutputCP() };
    let label = if acp == 936 { "gbk" } else { &format!("windows-{}", acp) };
    let encoding = Encoding::for_label_no_replacement(label.as_bytes()).unwrap_or(encoding_rs::UTF_8);
    for proc in new_processes {
        output.push_str(&format!("Process: {}\n", proc));
        // Escape dots for regex
        let escaped_proc = proc.replace(".", r"\.");
        let es_output = Command::new("es").args(["-utf8-bom", "-r", &format!("^{}$", escaped_proc)]).output();
        match es_output {
            Ok(output_result) if output_result.status.success() => {
                let stdout = &output_result.stdout;
                // Strip UTF-8 BOM if present
                let ansi_bytes = if stdout.starts_with(&[0xEF, 0xBB, 0xBF]) { &stdout[3..] } else { stdout };
                // Decode from console output codepage to UTF-8
                let (result, _, _) = encoding.decode(ansi_bytes);
                if !result.trim().is_empty() {
                    output.push_str("Found:\n");
                    for line in result.lines() {
                        output.push_str(&format!("  {}\n", line));
                    }
                } else {
                    output.push_str("Not found, result empty\n");
                }
            }
            _ => {
                output.push_str("Not found, es failed\n");
            }
        }
        output.push_str("---\n");
    }

    if let Err(e) = std::fs::write(output_file, output) {
        log!("Failed to write output: {}", e);
    } else {
        log!("Results saved to {}", output_file);
    }
}

fn main() -> windows::core::Result<()> {
    let args: Vec<String> = env::args().collect();
    let mut cli = CliArgs::new();
    parse_args(&args, &mut cli)?;
    if cli.help_mode {
        print_help();
        return Ok(());
    }
    if cli.help_all_mode {
        print_help_all();
        return Ok(());
    }
    if cli.convert_mode {
        convert(cli.in_file_name, cli.out_file_name);
        return Ok(());
    }
    let config_result = read_config(&cli.config_file_name);
    // avoid redundant log output after elevation, which starts a new process of this service
    *DUST_BIN_MODE.lock().unwrap() = cli.skip_log_before_elevation;
    config_result.print_report();
    if !config_result.errors.is_empty() {
        log!("Configuration file has errors, please fix them before running the service.");
        return Ok(());
    }
    if cli.validate_mode {
        return Ok(());
    }
    let mut configs = config_result.configs;
    let mut blacklist = if let Some(ref bf) = cli.blacklist_file_name {
        read_list(bf).unwrap_or_default()
    } else {
        Vec::new()
    };

    let mut last_config_mod_time = std::fs::metadata(&cli.config_file_name).and_then(|m| m.modified()).ok();
    let mut last_blacklist_mod_time = cli.blacklist_file_name.as_ref().and_then(|bf| std::fs::metadata(bf).and_then(|m| m.modified()).ok());
    let is_config_empty = configs.is_empty();
    let is_blacklist_empty = blacklist.is_empty();
    if cli.process_logs_mode {
        process_logs(&configs, &blacklist, cli.in_file_name.as_deref(), cli.out_file_name.as_deref());
        return Ok(());
    }
    if is_config_empty && is_blacklist_empty {
        if !cli.find_mode {
            log!("not even a single config, existing");
            return Ok(());
        }
    } else {
        log!("{} blacklist items load", blacklist.len());
    }

    if !cli.no_debug_priv {
        enable_debug_privilege();
    } else {
        log!("SeDebugPrivilege disabled by -noDebugPriv flag");
    }
    if !cli.no_inc_base_priority {
        enable_inc_base_priority_privilege();
    } else {
        log!("SeIncreaseBasePriorityPrivilege disabled by -noIncBasePriority flag");
    }

    if cli.time_resolution != 0 {
        unsafe {
            let mut current_resolution = 0u32;
            match NtSetTimerResolution(cli.time_resolution, true, &mut current_resolution as *mut _ as *mut std::ffi::c_void).0 {
                ntstatus if ntstatus < 0 => {
                    log!("Failed to set timer resolution: 0x{:08X}", ntstatus);
                }
                ntstatus if ntstatus >= 0 => {
                    log!("Succeed to set timer resolution: {:.4}ms", cli.time_resolution as f64 / 10000f64);
                    log!("elder timer resolution: {:.4}ms", current_resolution);
                }
                _ => {}
            };
        }
    }
    log!("Affinity Service started with time interval: {}", cli.interval_ms);

    if !is_running_as_admin() {
        if cli.no_uac {
            log!("Not running as administrator. UAC elevation disabled by -noUAC flag.");
            log!("Warning: May not be able to manage all processes without admin privileges.");
        } else {
            log!("Not running as administrator. Requesting UAC elevation...");
            match request_uac_elevation(*use_console().lock().unwrap()) {
                Ok(_) => {
                    log!("Running with administrator privileges.");
                }
                Err(e) => {
                    log!("Failed to request elevation: {}, may not manage all processes", e);
                }
            }
        }
    }
    *DUST_BIN_MODE.lock().unwrap() = false;
    let mut prime_core_scheduler = PrimeThreadScheduler::new(config_result.constants);
    let mut current_loop = 0u32;
    let mut should_continue = true;

    while should_continue {
        if cli.log_loop {
            log!("Loop {} started", current_loop + 1);
        }
        match ProcessSnapshot::take() {
            Ok(mut processes) => {
                let mut total_changes = 0;
                let pids_and_names: Vec<(u32, String)> = processes.pid_to_process.values().map(|p| (p.pid(), p.get_name().to_string())).collect();
                prime_core_scheduler.reset_alive();

                // Iterate through graded configs: apply rules only when current_loop % grade == 0
                for (grade, grade_configs) in &configs {
                    // current_loop is 0-based, so we apply grade 1 rules every loop (0 % 1 == 0, 1 % 1 == 0, etc.)
                    if !current_loop.is_multiple_of(*grade) {
                        continue; // Skip this grade this loop
                    }

                    for (pid, name) in &pids_and_names {
                        if let Some(config) = grade_configs.get(name) {
                            let result = apply_config(*pid, config, &mut prime_core_scheduler, Some(&mut processes), cli.dry_run);
                            if !result.is_empty() {
                                // Log errors to find log
                                for error in &result.errors {
                                    log_to_find(error);
                                }
                                // Log changes to main log
                                if !result.changes.is_empty() {
                                    let first = format!("{:>5}::{}::{}", pid, config.name, result.changes[0]);
                                    log_message(&first);
                                    let padding = " ".repeat(first.len() - result.changes[0].len() + 10);
                                    for change in &result.changes[1..] {
                                        log_pure_message(&format!("{}{}", padding, change));
                                    }
                                }

                                total_changes += result.changes.len();
                            }
                        }
                    }
                }
                prime_core_scheduler.close_dead_process_handles();
                if cli.dry_run {
                    let total_rules: usize = configs.values().map(|g| g.len()).sum();
                    log!(
                        "[DRY RUN] Checking {} running processes against {} config rules...",
                        processes.pid_to_process.len(),
                        total_rules
                    );
                    log!("[DRY RUN] {} change(s) would be made. Run without -dryrun to apply.", total_changes);
                    should_continue = false;
                }

                drop(processes);
            }
            Err(err) => {
                log!("Failed to take process snapshot: {}", err);
            }
        };
        if cli.find_mode {
            unsafe {
                let snapshot = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0)?;
                let mut pe32 = PROCESSENTRY32W {
                    dwSize: size_of::<PROCESSENTRY32W>() as u32,
                    ..Default::default()
                };
                if Process32FirstW(snapshot, &mut pe32).is_ok() {
                    loop {
                        let process_name = String::from_utf16_lossy(&pe32.szExeFile[..pe32.szExeFile.iter().position(|&c| c == 0).unwrap_or(0)]).to_lowercase();
                        // Check if process exists in any grade bucket
                        let in_configs = configs.values().any(|grade_configs| grade_configs.contains_key(&process_name));
                        if !FAIL_SET.lock().unwrap().contains(&process_name)
                            && !in_configs
                            && !blacklist.contains(&process_name)
                            && is_affinity_unset(pe32.th32ProcessID, process_name.as_str())
                        {
                            log_process_find(&process_name);
                        }
                        if Process32NextW(snapshot, &mut pe32).is_err() {
                            break;
                        }
                    }
                }
                let _ = CloseHandle(snapshot);
            }
        }
        let _ = find_logger().lock().unwrap().flush();
        let _ = logger().lock().unwrap().flush();
        current_loop += 1;
        if let Some(max_loops) = cli.loop_count
            && current_loop >= max_loops
        {
            if cli.log_loop {
                log!("Completed {} loops, exiting", max_loops);
            }
            should_continue = false;
        }
        if should_continue {
            thread::sleep(Duration::from_millis(cli.interval_ms));
            *LOCALTIME_BUFFER.lock().unwrap() = Local::now();

            // Check for config reload
            if let Ok(metadata) = std::fs::metadata(&cli.config_file_name)
                && let Ok(mod_time) = metadata.modified()
                && Some(mod_time) != last_config_mod_time
            {
                last_config_mod_time = Some(mod_time);
                log!("Configuration file '{}' changed, reloading...", cli.config_file_name);
                let new_config_result = read_config(&cli.config_file_name);
                if new_config_result.errors.is_empty() {
                    new_config_result.print_report();
                    let total_rules = new_config_result.total_rules();
                    configs = new_config_result.configs;
                    prime_core_scheduler.constants = new_config_result.constants;
                    log!("Configuration reload complete: {} rules loaded.", total_rules);
                } else {
                    log!("Configuration file '{}' has errors, keeping previous configuration.", cli.config_file_name);
                    for error in &new_config_result.errors {
                        log!("  - {}", error);
                    }
                }
            }

            // Check for blacklist reload
            if let Some(ref bf) = cli.blacklist_file_name {
                match std::fs::metadata(bf) {
                    Err(_) => {
                        if last_blacklist_mod_time.is_some() {
                            last_blacklist_mod_time = None;
                            log!("Blacklist file '{}' no longer accessible, clearing blacklist.", bf);
                            blacklist.clear();
                        }
                    }
                    Ok(metadata) => {
                        if let Ok(mod_time) = metadata.modified()
                            && Some(mod_time) != last_blacklist_mod_time
                        {
                            last_blacklist_mod_time = Some(mod_time);
                            log!("Blacklist file '{}' changed, reloading...", bf);
                            blacklist = read_list(bf).unwrap_or_default();
                            log!("Blacklist reload complete: {} items loaded.", blacklist.len());
                        }
                    }
                }
            }
        }
    }
    Ok(())
}
