pub fn error_from_code(code: u32) -> String {
    match code {
        0 => "SUCCESS".to_string(),
        2 => "FILE_NOT_FOUND".to_string(),
        5 => "ACCESS_DENIED".to_string(),
        6 => "INVALID_HANDLE".to_string(),
        8 => "NOT_ENOUGH_MEMORY".to_string(),
        87 => "INVALID_PARAMETER".to_string(),
        122 => "INSUFFICIENT_BUFFER".to_string(),
        126 => "MOD_NOT_FOUND".to_string(),
        127 => "PROC_NOT_FOUND".to_string(),
        193 => "BAD_EXE_FORMAT".to_string(),
        565 => "TOO_MANY_THREADS".to_string(),
        566 => "THREAD_NOT_IN_PROCESS".to_string(),
        567 => "PAGEFILE_QUOTA_EXCEEDED".to_string(),
        571 => "IO_PRIVILEGE_FAILED".to_string(),
        577 => "INVALID_IMAGE_HASH".to_string(),
        633 => "DRIVER_FAILED_SLEEP".to_string(),
        998 => "NOACCESS".to_string(),
        1003 => "CALLER_CANNOT_MAP_VIEW".to_string(),
        1006 => "VOLUME_CHANGED".to_string(),
        1007 => "FULLSCREEN_MODE".to_string(),
        1008 => "INVALID_HANDLE_STATE".to_string(),
        1058 => "SERVICE_DISABLED".to_string(),
        1060 => "SERVICE_DOES_NOT_EXIST".to_string(),
        1062 => "SERVICE_NOT_STARTED".to_string(),
        1073 => "ALREADY_RUNNING".to_string(),
        1314 => "PRIVILEGE_NOT_HELD".to_string(),
        1330 => "INVALID_ACCOUNT_NAME".to_string(),
        1331 => "LOGON_FAILURE".to_string(),
        1332 => "ACCOUNT_RESTRICTION".to_string(),
        1344 => "NO_LOGON_SERVERS".to_string(),
        1346 => "RPC_AUTH_LEVEL_MISMATCH".to_string(),
        1444 => "INVALID_THREAD_ID".to_string(),
        1445 => "NON_MDICHILD_WINDOW".to_string(),
        1450 => "NO_SYSTEM_RESOURCES".to_string(),
        1460 => "TIMEOUT".to_string(),
        1453 => "QUOTA_EXCEEDED".to_string(),
        1455 => "PAGEFILE_TOO_SMALL".to_string(),
        1500 => "EVT_INVALID_CHANNEL".to_string(),
        1503 => "EVT_CHANNEL_ALREADY_EXISTS".to_string(),
        _ => format!("ERROR_CODE_{}", code),
    }
}
